baseURL: https://jiayebaiwebsite.netlify.app/
languageCode: en-us
title: Portfolio website for Jiaye Bai
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      My PORTFOLIO WEBSITE RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Jiaye
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jbai.mfa2022@london.com
        title: Email
    enable: yes
    phone:
      - phone: (044) 07428580431
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
 #       label: Twitter
  #      url: https://www.twitter.com
#      - icon: fa-facebook
 #       label: Facebook
  #      url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/umaruuugo/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/JiayeB
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jiaye-bai-a4b714182/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: frontpage01.jpg
        subtitle: Short biography
        title: About me
        url: blogs/about_me
      - image: investment_banking.jpg
        subtitle: Short resume
        title: My CV
        url: blogs/my_cv
      - image: computer.jpg
        subtitle: R project showcase
        title: My R work
        url: blogs/imdb
      - image: yolo.jpg
        subtitle: YOLO
        title: Hobbies & Interests
        url: blogs/yolo
      - image: disney.jpg
        subtitle: Adventures and exporation
        title: My Gap year
        url: blogs/gap_year
      - image: next.jpg
        subtitle: To do list for future
        title: My future
        url: blogs/my_future
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Keep your eyes on the stars and your feet on the ground."
    title: Life motto 
    url: blogs
